sensor:
- platform: template
  sensors:
    programmschalter_with_icon:
      friendly_name: "Programmschalter with Icon"
      value_template: "{{ states('sensor.programmschalter') }}"
      icon_template: >-
        {% if is_state('sensor.programmschalter', 'Notbetrieb') %}
          mdi:power-off
        {% elif is_state('sensor.programmschalter', 'Bereitschaft') %}
          mdi:flash
        {% elif is_state('sensor.programmschalter', 'Automatik') %}
          mdi:weather-sunny
        {% elif is_state('sensor.programmschalter', 'Tagbetrieb') %}
          mdi:white-balance-sunny
        {% elif is_state('sensor.programmschalter', 'Absenkbetrieb') %}
          mdi:thermometer-chevron-down
        {% elif is_state('sensor.programmschalter', 'Warmwasser') %}
          mdi:water
        {% else %}
          mdi:help-circle
        {% endif %}
    sommerbetrieb_text:
      unique_id: 0c0078f8-8347-4b47-8bff-8510815b71f3
      friendly_name: "Betriebsart"
      value_template: >-
        {% if is_state('sensor.sommerbetrieb', 'on') %}
          Sommerbetrieb
        {% else %}
          Normalbetrieb
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.sommerbetrieb', 'on') %}
          mdi:white-balance-sunny
        {% else %}
          mdi:circle-outline
        {% endif %}

input_number:
  speichersolltemp2_set:
    name: "SPEICHERSOLLTEMP2_SET"
    initial: 20
    min: 20
    max: 60
    mode: box
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermometer-low
  
  speichersolltemp_set:
    name: "SPEICHERSOLLTEMP_SET"
    initial: 20
    min: 20
    max: 60
    mode: box
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermometer-high